# Generated by Django 3.1.3 on 2020-11-27 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_auto_20201127_1751'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Domicio',
            new_name='Domicilio',
        ),
    ]
